source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'SOTProgressHUD_Example', :exclusive => true do
  pod "SOTProgressHUD", :path => "../"
end

target 'SOTProgressHUD_Tests', :exclusive => true do
  pod "SOTProgressHUD", :path => "../"

  
end
