language: objective-c
osx_image: xcode7.2

before_install:
- gem install xcpretty -N
- gem install cocoapods
- xcodebuild -version

# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example

script:
- xcodebuild clean
- set -o pipefail && xcodebuild test -workspace Example/SOTProgressHUD.xcworkspace -scheme SOTProgressHUD-Example -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
